_wandb:
    value:
        cli_version: 0.29.0
        e:
            uob6jcekfmfx8188ckj4arr8jea200dh:
                args:
                    - --config
                    - configs/federated/exp45_fedgrid_fedprox_r20/node_kau-bcmd.yaml
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "195722883072"
                        used: "139190784000"
                executable: /media/imagenesmedicas/DATA1/01-ImagenesMedicas-US1/13-PregradoJulian/Federal Learning/infraestructura federada/FedMammoBench/.venv/bin/python
                git:
                    commit: ae50d4cf888238a1dc2aa5557ba3eab283c1febf
                    remote: git@github.com:Ayax911/FedMammoBench.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-c5b5be7b-8c3e-86ad-6240-79778baae0e8
                host: labmirp-Precision-5860-Tower
                memory:
                    total: "134269358080"
                os: Linux-7.0.0-28-generic-x86_64-with-glibc2.39
                program: -m src.federated.client
                python: CPython 3.12.8
                root: runs/exp45_fedgrid_fedprox_r20/nodes/kau-bcmd
                startedAt: "2026-09-11T06:10:21.577731Z"
                writerId: uob6jcekfmfx8188ckj4arr8jea200dh
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
                - 62
                - 61
                - 78
            "4": 3.12.8
            "5": 0.29.0
            "12": 0.29.0
            "13": linux-x86_64
aggregation_scope:
    value: full
architecture:
    value:
        name: resnet50_imagenet_v2
        unfreeze_from: conv1
        weights_path: null
data:
    value:
        augmentation:
            blur: true
            blur_p: 0.3
            horizontal_flip: true
            horizontal_flip_p: 0.5
            rotation_degrees: 15
            vertical_flip: true
            vertical_flip_p: 0.2
        batch_size: 64
        by_database_manifests: null
        image_root: /media/imagenesmedicas/DATA1/01-ImagenesMedicas-US1/02-Databases/Mammo-Bench/c86fb00c-0fb8-4e0e-85a2-4d415f9c1ada_1a9410d8-9769-4064-a064-0160f2fd193d_DATASET-FILE_Mammo_Bench_zip_20241225112148174/Mammo_Data/Mammo-Bench/preproccesed_julian
        image_size: null
        manifest_path: manifests/by_database/kau-bcmd_norm_0_1.csv
        normalize_mean:
            - 0.449
        normalize_std:
            - 0.226
        num_workers: 0
        seed: 42
experiment_id:
    value: exp45_fedgrid_fedprox_r20
head:
    value:
        hparams:
            activation: leakyrelu
            dropout: 0
            hidden_layers:
                - 512
            in_features: 2048
            input_dropout: 0.446757081317639
            negative_slope: 0.2
            num_classes: 2
        name: configurable_mlp
loss:
    value:
        hparams:
            label_smoothing: 0.013689308712627246
            weight:
                - 0.524447086799881
                - 10.75609756097561
        name: cross_entropy
node_name:
    value: kau-bcmd
optimizer:
    value:
        hparams:
            backbone_lr: 0.00020959745042706368
            betas:
                - 0.5
                - 0.999
            lr: 0.0006453040132730183
            weight_decay: 0.0003423573093420121
        name: adamw
run:
    value:
        checkpoint_dir: runs/exp45_fedgrid_fedprox_r20/nodes/kau-bcmd/weights
        device: cuda
        freeze_bn_stats: true
        run_dir: runs/exp45_fedgrid_fedprox_r20/nodes/kau-bcmd
        wandb_group: exp45_fedgrid_fedprox_r20
        wandb_project: fedmammobench2.0
scheduler:
    value: null
server_address:
    value: 127.0.0.1:8084
