_wandb:
    value:
        cli_version: 0.29.0
        e:
            b72wpnjwmhzs5ge6fpcth5ydmti47udm:
                args:
                    - --config
                    - configs/exp02.yaml
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "195722883072"
                        used: "138013560832"
                executable: /media/imagenesmedicas/DATA1/01-ImagenesMedicas-US1/13-PregradoJulian/Federal Learning/infraestructura federada/FedMammoBench/.venv/bin/python
                git:
                    commit: 2c831bf29ae482d0b24995bca83e5632266e7a13
                    remote: git@github.com:Ayax911/FedMammoBench.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-c5b5be7b-8c3e-86ad-6240-79778baae0e8
                host: labmirp-Precision-5860-Tower
                memory:
                    total: "134269358080"
                os: Linux-7.0.0-28-generic-x86_64-with-glibc2.39
                program: -m src.cli
                python: CPython 3.12.8
                root: runs/Classification_Images_HL1024-512_lr1e-4_dr0.2
                startedAt: "2026-08-31T19:56:36.569645Z"
                writerId: b72wpnjwmhzs5ge6fpcth5ydmti47udm
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
            "4": 3.12.8
            "5": 0.29.0
            "12": 0.29.0
            "13": linux-x86_64
