experiment_id: exp21_pretrain_ablation_radimagenet_layer4.yaml
architecture:
  name: resnet50_radimagenet
  weights_path: /media/imagenesmedicas/DATA1/01-ImagenesMedicas-US1/13-PregradoJulian/Federal
    Learning/infraestructura federada/FedMammoBench/weights/ResNet50.pt
  unfreeze_from: layer4
head:
  name: configurable_mlp
  hparams:
    in_features: 2048
    hidden_layers: []
    activation: leakyrelu
    negative_slope: 0.2
    dropout: 0.0
    num_classes: 2
optimizer:
  name: adam
  hparams:
    lr: 0.0001
    betas:
    - 0.5
    - 0.999
scheduler:
  name: cosine
  hparams:
    T_max: 200
    eta_min: 1.0e-06
loss:
  name: cross_entropy
  hparams:
    weight:
    - 0.7593
    - 1.4642
data:
  manifest_path: manifests/fedmammobench_norm_0_1.csv
  image_root: /media/imagenesmedicas/DATA1/01-ImagenesMedicas-US1/02-Databases/Mammo-Bench/c86fb00c-0fb8-4e0e-85a2-4d415f9c1ada_1a9410d8-9769-4064-a064-0160f2fd193d_DATASET-FILE_Mammo_Bench_zip_20241225112148174/Mammo_Data/Mammo-Bench/preproccesed_julian
  batch_size: 64
  num_workers: 4
  seed: 42
  image_size: null
  augmentation:
    horizontal_flip: true
    horizontal_flip_p: 0.5
    rotation_degrees: 15
    vertical_flip: true
    vertical_flip_p: 0.2
    blur: true
    blur_p: 0.3
  normalize_mean: null
  normalize_std: null
  by_database_manifests:
    cmmd: manifests/by_database/cmmd_norm_0_1.csv
    cdd-cesm: manifests/by_database/cdd-cesm_norm_0_1.csv
    inbreast: manifests/by_database/inbreast_norm_0_1.csv
    kau-bcmd: manifests/by_database/kau-bcmd_norm_0_1.csv
train:
  epochs: 200
  metric_name: f1_macro
  metric_mode: max
  patience: 100
  min_delta: 0.005
  save_every: 10
  checkpoint_dir: runs/exp21_pretrain_ablation_radimagenet_layer4/weights
  run_dir: runs/exp21_pretrain_ablation_radimagenet_layer4
  device: cuda
  freeze_bn_stats: false
  wandb_project: fedmammobench2.0
  wandb_group: pretrain_ablation_imagenet_vs_radimagenet
